!classDefinition: #BooleanTests category: 'Booleanos'!
DenotativeObject subclass: #BooleanTests
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Booleanos'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'BooleanTests class' category: 'Booleanos'!
BooleanTests class
	instanceVariableNames: ''!

!BooleanTests class methodsFor: 'Tests' stamp: 's 3/30/2023 19:29:36'!
LuzAmarilla apagar.
	(Delay for: 0.5 * second) wait.
	
	LuzAmarilla  prender.
	(Delay for: 0.5 * second) wait.
	LuzAmarilla apagar.
	(Delay for: 0.5 * second) wait.
	! !

!BooleanTests class methodsFor: 'Tests' stamp: 's 3/30/2023 19:29:36'!
.
	
	LuzAmarilla  prender.
	(Delay for: 0.5 * second) wait.
	LuzAmarilla apagar.
	(Delay for: 0.5 * second) wait.
	! !

!BooleanTests class methodsFor: 'Tests'!
3/30/2023 19:30:26'! !

!BooleanTests class methodsFor: 'Tests' stamp: 's 3/30/2023 19:08:27'!
apagar.
	(Delay for: 0.5 * second) wait.
	
		LuzAmarilla  prender.
	(Delay for: 0.5 * second) wait.
	LuzAmarilla apagar.
	(Delay for: 0.5 * second) wait.
	! !

!BooleanTests class methodsFor: 'Tests' stamp: 's 3/30/2023 19:10:37'!
: 0.5 * second) wait.
	
		LuzAmarilla  prender.
	(Delay for: 0.5 * second) wait.
	LuzAmarilla apagar.
	(Delay for: 0.5 * second) wait.
	
		LuzAmarilla  prender.
	(Delay for: 0.5 * second) wait.
	LuzAmarilla apagar.
	(Delay for: 0.5 * second) wait.
	
		LuzAmarilla  prender.
	(Delay for: 0.5 * second) wait.
	LuzAmarilla apagar.
	(Delay for: 0.5 * second) wait.
	
	LuzAmarilla  prender.
	(Delay for: 0.5 * second) wait.
	LuzAmarilla apagar.
	(Delay for: 0.5 * second) wait.
	! !

!BooleanTests class methodsFor: 'Tests' stamp: 's 3/30/2023 19:10:37'!
(Delay for: 0.5 * second) wait.
	LuzAmarilla apagar.
	(Delay for: 0.5 * second) wait.
	
		LuzAmarilla  prender.
	(Delay for: 0.5 * second) wait.
	LuzAmarilla apagar.
	(Delay for: 0.5 * second) wait.
	
	LuzAmarilla  prender.
	(Delay for: 0.5 * second) wait.
	LuzAmarilla apagar.
	(Delay for: 0.5 * second) wait.
	! !

!BooleanTests class methodsFor: 'Tests' stamp: 's 3/30/2023 19:10:37'!
d) wait.
	
	LuzAmarilla  prender.
	(Delay for: 0.5 * second) wait.
	LuzAmarilla apagar.
	(Delay for: 0.5 * second) wait.
	! !

!BooleanTests class methodsFor: 'Tests' stamp: 's 3/30/2023 19:10:50'!
: 0.5 * second) wait.
	
	LuzAmarilla  prender.
	(Delay for: 0.5 * second) wait.
	LuzAmarilla apagar.
	(Delay for: 0.5 * second) wait.
	
	LuzAmarilla  prender.
	(Delay for: 0.5 * second) wait.
	LuzAmarilla apagar.
	(Delay for: 0.5 * second) wait.
	
	LuzAmarilla  prender.
	(Delay for: 0.5 * second) wait.
	LuzAmarilla apagar.
	(Delay for: 0.5 * second) wait.
	
	LuzAmarilla  prender.
	(Delay for: 0.5 * second) wait.
	LuzAmarilla apagar.
	(Delay for: 0.5 * second) wait.
	! !

!BooleanTests class methodsFor: 'Tests' stamp: 's 3/30/2023 19:10:50'!
wait.
	
	LuzAmarilla  prender.
	(Delay for: 0.5 * second) wait.
	LuzAmarilla apagar.
	(Delay for: 0.5 * second) wait.
	! !

!BooleanTests class methodsFor: 'Tests'!
0/2023 19:10:54' prior: 50604144! !

!BooleanTests class methodsFor: 'Tests'!
! !

!BooleanTests class methodsFor: 'Tests'!
! !

!BooleanTests class methodsFor: 'Tests'!
:34:10' prior: 50604301! !

!BooleanTests class methodsFor: 'Tests'!
! !


!classDefinition: #Falso category: 'Booleanos'!
DenotativeObject subclass: #Falso
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Booleanos'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'Falso class' category: 'Booleanos'!
Falso class
	instanceVariableNames: ''!

!Falso class methodsFor: 'operators' stamp: 's 3/30/2023 19:29:36'!
ay for: 0.5 * second) wait.
	LuzAmarilla apagar.
	(Delay for: 0.5 * second) wait.
	
	LuzAmarilla  prender.
	(Delay for: 0.5 * second) wait.
	LuzAmarilla apagar.
	(Delay for: 0.5 * second) wait.
	
	LuzAmarilla  prender.
	(Delay for: 0.5 * second) wait.
	LuzAmarilla apagar.
	(Delay for: 0.5 * second) wait.
	! !

!Falso class methodsFor: 'operators'!
methodsFor: 'metodos' stamp: 's 3/30/2023 19:08:27' prior: 50604026! !

!Falso class methodsFor: 'operators' stamp: 's 3/30/2023 19:30:26'!
(Delay for: 0.5 * second) wait! !

!Falso class methodsFor: 'operators' stamp: 's 3/30/2023 19:29:36'!
.
	
	LuzAmarilla  prender.
	(Delay for: 0.5 * second) wait.
	LuzAmarilla apagar.
	(Delay for: 0.5 * second) wait.
	! !

!Falso class methodsFor: 'operators' stamp: 's 3/30/2023 19:06:07'!
ariableNames: ''
	poolDictionaries: ''
	category: 'Semaforo'! !


!classDefinition: #Verdadero category: 'Booleanos'!
DenotativeObject subclass: #Verdadero
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Booleanos'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'Verdadero class' category: 'Booleanos'!
Verdadero class
	instanceVariableNames: ''!

!Verdadero class methodsFor: 'operators' stamp: 's 3/30/2023 19:29:36'!
rilla apagar.
	(Delay for: 0.5 * second) wait.
	
	LuzAmarilla  prender.
	(Delay for: 0.5 * second) wait.
	LuzAmarilla apagar.
	(Delay for: 0.5 * second) wait.
	! !

!Verdadero class methodsFor: 'operators'!
3/30/2023 19:06:07'! !

!Verdadero class methodsFor: 'operators' stamp: 's 3/30/2023 19:29:36'!
render.
	(Delay for: 0.5 * second) wait.
	LuzAmarilla apagar.
	(Delay for: 0.5 * second) wait.
	! !

!Verdadero class methodsFor: 'operators' stamp: 's 3/30/2023 19:29:36'!
cond) wait.
	! !

!Verdadero class methodsFor: 'operators' stamp: 's 3/30/2023 19:05:59'!
eVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Semaforo'! !
